title = "HellPot"

[logger]
debug = true
log_directory = "./logs/" 

[http]
bind_addr = "127.0.0.1"
bind_port = "8080"
# paths to be added to robots.txt that we will respond to
paths = [
	"wp-login.php",
	"wp-login",
]
