name: Vibe Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: go vet -v ./...
        run: go vet -v ./...
      - name: gosec ./...
        uses: securego/gosec@master
          args: ./...
      - name: go build -v ./...
        run: go build -v ./...
